name: Test & Type Check

on: [push, pull_request]

jobs:
  test:
    name: Test & Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Pytest
      run: pytest
    - name: Type check
      run: mypy easy_transformer
